import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  books: [
    {
      id: 1,
      title: "Shadows at Noon",
      author: "Eli Grant",
      category: "Mystery",
      description:
        "A detective hunts a killer in a sleepy town turned sinister.",
      rating: 4.0,
      coverImage: "/images/shadows-at-noon.jpg",
    },
    {
      id: 2,
      title: "Stars Between Us",
      author: "Nina Carter",
      category: "Fiction",
      description: "Two souls find each other in a world torn apart.",
      rating: 4.5,
      coverImage: "/images/stars-between-us.jpg",
    },
    {
      id: 3,
      title: "The Science of Sleep",
      author: "Dr. Alan Brooks",
      category: "Non-Fiction",
      description: "An insightful journey into the world of dreams and rest.",
      rating: 4.2,
      coverImage: "/images/science-sleep.jpg",
    },
    {
      id: 4,
      title: "Quantum Dilemma",
      author: "Neil Archer",
      category: "Sci-Fi",
      description:
        "A physicist’s experiment with time opens the door to multiple realities.",
      rating: 4.4,
      coverImage: "/images/quantum-dilemma.jpg",
    },
    {
      id: 5,
      title: "Whispers in the Fog",
      author: "Clara West",
      category: "Mystery",
      description: "When the fog rolls in, secrets rise with it.",
      rating: 4.1,
      coverImage: "/images/whispers-fog.jpg",
    },
    {
      id: 6,
      title: "Ink & Ashes",
      author: "Marissa Lane",
      category: "Fiction",
      description: "A poetic tale of grief, healing, and rediscovery.",
      rating: 4.3,
      coverImage: "/images/ink-ashes.jpg",
    },
    {
      id: 7,
      title: "Artificial Eden",
      author: "Leo Tran",
      category: "Sci-Fi",
      description:
        "A society engineered by AI begins to crumble under emotion.",
      rating: 4.5,
      coverImage: "/images/artificial-eden.jpg",
    },
    {
      id: 8,
      title: "Behind the Ink",
      author: "Natalie Kim",
      category: "Non-Fiction",
      description:
        "Exploring the stories of famous tattoos and the artists behind them.",
      rating: 4.2,
      coverImage: "/images/behind-ink.jpg",
    },
    {
      id: 9,
      title: "Lost Signal",
      author: "Dana Frost",
      category: "Mystery",
      description:
        "A missing journalist. A cryptic recording. A town with no answers.",
      rating: 4.0,
      coverImage: "/images/lost-signal.jpg",
    },
    {
      id: 10,
      title: "Memoirs of a Mountain",
      author: "Elliot Faye",
      category: "Biography",
      description:
        "The inspiring story of a mountaineer who overcame the odds.",
      rating: 4.7,
      coverImage: "/images/memoirs-mountain.jpg",
    },

    {
      id: 11,
      title: "The Fifth String",
      author: "Javier DeMarco",
      category: "Fiction",
      description: "A story of forbidden music in a dystopian regime.",
      rating: 4.5,
      coverImage: "/images/fifth-string.jpg",
    },
    {
      id: 12,
      title: "The Cosmos Within",
      author: "Amara Deen",
      category: "Non-Fiction",
      description: "Understanding the universe and our place in it.",
      rating: 4.3,
      coverImage: "/images/cosmos-within.jpg",
    },
    {
      id: 13,
      title: "The Ghost Protocol",
      author: "Isaac Norton",
      category: "Sci-Fi",
      description: "AI resurrects a long-dead human as a digital entity.",
      rating: 4.1,
      coverImage: "/images/ghost-protocol.jpg",
    },
    {
      id: 14,
      title: "Voices in the Walls",
      author: "Harper Knox",
      category: "Mystery",
      description: "A haunted house and a voice that won’t go silent.",
      rating: 4.2,
      coverImage: "/images/voices-walls.jpg",
    },
    {
      id: 15,
      title: "Rise of the Red Phoenix",
      author: "Tessa Long",
      category: "Fiction",
      description: "A revolutionary tale of a forgotten empire rising again.",
      rating: 4.4,
      coverImage: "/images/red-phoenix.jpg",
    },
    {
      id: 16,
      title: "The Infinite Loop",
      author: "Ronan Wells",
      category: "Sci-Fi",
      description: "Time travelers stuck in a loop must find a way out.",
      rating: 4.0,
      coverImage: "/images/infinite-loop.jpg",
    },
    {
      id: 17,
      title: "Truths Untold",
      author: "Kim Reynolds",
      category: "Non-Fiction",
      description: "Revealing hidden historical truths that shaped nations.",
      rating: 4.6,
      coverImage: "/images/truths-untold.jpg",
    },
    {
      id: 18,
      title: "Walking with Giants",
      author: "Samuel J. Hart",
      category: "Biography",
      description: "The life of a man who stood tall in troubled times.",
      rating: 4.5,
      coverImage: "/images/walking-giants.jpg",
    },
    {
      id: 19,
      title: "Buried Secrets",
      author: "Emily Sloane",
      category: "Mystery",
      description:
        "A skeleton is found in a garden, unraveling generations of secrets.",
      rating: 4.3,
      coverImage: "/images/buried-secrets.jpg",
    },
    {
      id: 20,
      title: "Stellar Drift",
      author: "Maya Voss",
      category: "Sci-Fi",
      description: "A drifting spaceship. A lost mission. A cosmic conspiracy.",
      rating: 4.4,
      coverImage: "/images/stellar-drift.jpg",
    },

    {
      id: 21,
      title: "The Day We Remembered",
      author: "Victor Hale",
      category: "Fiction",
      description: "One town's reckoning with history, pain, and redemption.",
      rating: 4.1,
      coverImage: "/images/day-remembered.jpg",
    },
    {
      id: 22,
      title: "Unveiling Genius",
      author: "Dr. Lila Khan",
      category: "Biography",
      description: "Life of a misunderstood scientist who changed the world.",
      rating: 4.6,
      coverImage: "/images/unveiling-genius.jpg",
    },
    {
      id: 23,
      title: "Micro to Macro",
      author: "Cynthia Roe",
      category: "Non-Fiction",
      description: "The science of scaling ideas from small to massive.",
      rating: 4.0,
      coverImage: "/images/micro-macro.jpg",
    },
    {
      id: 24,
      title: "Into the Black",
      author: "Keiran Duke",
      category: "Sci-Fi",
      description: "A rebel pilot uncovers secrets in a forbidden galaxy.",
      rating: 4.3,
      coverImage: "/images/into-black.jpg",
    },
    {
      id: 25,
      title: "The Last Clue",
      author: "Jordan Myles",
      category: "Mystery",
      description: "A dying man's riddle sets off a thrilling treasure hunt.",
      rating: 4.2,
      coverImage: "/images/last-clue.jpg",
    },
    {
      id: 26,
      title: "A River Between Us",
      author: "Elisa Park",
      category: "Fiction",
      description: "A family divided by war must find their way home.",
      rating: 4.5,
      coverImage: "/images/river-between.jpg",
    },
    {
      id: 27,
      title: "Echoes of the Mind",
      author: "Raj Patel",
      category: "Non-Fiction",
      description: "A neuroscientist’s dive into consciousness and memory.",
      rating: 4.4,
      coverImage: "/images/echoes-mind.jpg",
    },
    {
      id: 28,
      title: "Code of Light",
      author: "Elon Stroud",
      category: "Sci-Fi",
      description: "Alien tech. Global threat. Only one hacker can save Earth.",
      rating: 4.1,
      coverImage: "/images/code-light.jpg",
    },
    {
      id: 29,
      title: "Ghosts of Avalon",
      author: "Becca Lane",
      category: "Mystery",
      description: "An old castle and a legend that never died.",
      rating: 4.0,
      coverImage: "/images/ghosts-avalon.jpg",
    },
    {
      id: 30,
      title: "Path of Fire",
      author: "Natalie James",
      category: "Biography",
      description: "The untold journey of a firefighter breaking barriers.",
      rating: 4.5,
      coverImage: "/images/path-fire.jpg",
    },

    {
      id: 31,
      title: "Dust in the Sunlight",
      author: "Fiona Grey",
      category: "Fiction",
      description: "A quiet romance under the harsh desert sky.",
      rating: 4.2,
      coverImage: "/images/dust-sunlight.jpg",
    },
    {
      id: 32,
      title: "Solar Warden",
      author: "Max Duval",
      category: "Sci-Fi",
      description: "Earth’s secret fleet prepares for interstellar defense.",
      rating: 4.6,
      coverImage: "/images/solar-warden.jpg",
    },
    {
      id: 33,
      title: "Unmasked",
      author: "Jamie Rowe",
      category: "Biography",
      description: "A masked wrestler’s rise from slums to stardom.",
      rating: 4.3,
      coverImage: "/images/unmasked.jpg",
    },
    {
      id: 34,
      title: "In Plain Sight",
      author: "Talia Fern",
      category: "Mystery",
      description: "A killer hides among friends. Can anyone be trusted?",
      rating: 4.1,
      coverImage: "/images/plain-sight.jpg",
    },
    {
      id: 35,
      title: "The Memory Script",
      author: "Chloe North",
      category: "Sci-Fi",
      description: "A tech that edits memory falls into the wrong hands.",
      rating: 4.2,
      coverImage: "/images/memory-script.jpg",
    },
    {
      id: 36,
      title: "Open Water",
      author: "Riley Hammond",
      category: "Non-Fiction",
      description: "Lessons learned from extreme survival at sea.",
      rating: 4.4,
      coverImage: "/images/open-water.jpg",
    },
    {
      id: 37,
      title: "After the Storm",
      author: "Claire Hudson",
      category: "Fiction",
      description: "A woman rebuilds her life after a devastating hurricane.",
      rating: 4.0,
      coverImage: "/images/after-storm.jpg",
    },
    {
      id: 38,
      title: "Parallel",
      author: "Nico Torres",
      category: "Sci-Fi",
      description: "Two versions of Earth. One war. One chance to stop it.",
      rating: 4.3,
      coverImage: "/images/parallel.jpg",
    },
    {
      id: 39,
      title: "The Puzzle Box",
      author: "Greg Mann",
      category: "Mystery",
      description:
        "A mysterious box reveals connections to five unsolved cases.",
      rating: 4.5,
      coverImage: "/images/puzzle-box.jpg",
    },
    {
      id: 40,
      title: "Born to Run",
      author: "Jessie Miles",
      category: "Biography",
      description:
        "A sprinter's relentless rise from adversity to Olympic glory.",
      rating: 4.7,
      coverImage: "/images/born-run.jpg",
    },

    {
      id: 41,
      title: "Beneath the Willow",
      author: "Samantha Hope",
      category: "Fiction",
      description: "Secrets bloom beneath an old tree in rural Georgia.",
      rating: 4.2,
      coverImage: "/images/beneath-willow.jpg",
    },
    {
      id: 42,
      title: "Legacy of Steel",
      author: "Omar Quinn",
      category: "Biography",
      description: "How a blacksmith's tools built a modern dynasty.",
      rating: 4.4,
      coverImage: "/images/legacy-steel.jpg",
    },
    {
      id: 43,
      title: "Ocean Depths",
      author: "Dr. Helen Wu",
      category: "Non-Fiction",
      description: "Unraveling the mysteries of Earth's final frontier.",
      rating: 4.1,
      coverImage: "/images/ocean-depths.jpg",
    },
    {
      id: 44,
      title: "Hollow Earth",
      author: "Devon Sky",
      category: "Sci-Fi",
      description: "Explorers find life in the planet's forgotten core.",
      rating: 4.5,
      coverImage: "/images/hollow-earth.jpg",
    },
    {
      id: 45,
      title: "The Final Witness",
      author: "Olive Black",
      category: "Mystery",
      description: "Only one person knows the truth — but they’ve vanished.",
      rating: 4.3,
      coverImage: "/images/final-witness.jpg",
    },
    {
      id: 46,
      title: "The Forgotten Orchard",
      author: "Mae Bell",
      category: "Fiction",
      description: "Generations of secrets blossom in an old orchard.",
      rating: 4.3,
      coverImage: "/images/forgotten-orchard.jpg",
    },
    {
      id: 47,
      title: "Rising Tide",
      author: "Luke Anders",
      category: "Non-Fiction",
      description:
        "A look at climate change from the eye of coastal communities.",
      rating: 4.2,
      coverImage: "/images/rising-tide.jpg",
    },
    {
      id: 48,
      title: "Blueprints of Change",
      author: "Dr. Ava Lin",
      category: "Non-Fiction",
      description: "Engineering innovation that’s reshaping the world.",
      rating: 4.5,
      coverImage: "/images/blueprints-change.jpg",
    },
    {
      id: 49,
      title: "Lifelines",
      author: "Tyra Dane",
      category: "Biography",
      description: "A trauma nurse shares tales from the front lines.",
      rating: 4.6,
      coverImage: "/images/lifelines.jpg",
    },
    {
      id: 50,
      title: "Binary Hearts",
      author: "Juno Price",
      category: "Sci-Fi",
      description: "A human falls for a sentient android in a digital utopia.",
      rating: 4.4,
      coverImage: "/images/binary-hearts.jpg",
    },
  ],
};

const booksSlice = createSlice({
  name: "books",
  initialState,
  reducers: {
    addBook: (state, action) => {
      state.books.push(action.payload);
    },
  },
});

export const { addBook } = booksSlice.actions;
export default booksSlice.reducer;
